http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        forceSTSHeader: true
        sslProxyHeaders:
          X-Forwarded-Proto: https
        contentTypeNosniff: true
        referrerPolicy: "same-origin"
